## It seems like the yml file can control certain things (directories, toc, etc.) but doesn't work for other things (chunk_output_type). In summary, the _yml file is important still. 

project:
  type: default
  execute-dir: project
  output-dir: Rendered/
  pre-render: ../../Rcookbook/clean_stale_render_output.R
  post-render: ../../Rcookbook/flatten_rendered_pdf.R
format: 
  pdf: 
    header-includes:
      - |
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
    pdf-engine: lualatex
    author-affiliations: true
    template-partials:
      - Suppfiles/title.tex
editor_options:
  chunk_output_type: console
date: today
date-format: long